apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agderfk-no
resources:
  - ../../../base
commonLabels:
  app.kubernetes.io/instance: fint-samtykke-frontend-v2_agderfk_no
  fintlabs.no/org-id: agderfk.no
patches:
  - patch: |-
      - op: replace
        path: "/spec/orgId"
        value: "agderfk.no"
      - op: replace
        path: "/spec/url/basePath"
        value: "/agderfk-no"
      - op: replace
        path: "/spec/url/hostname"
        value: "samtykke.novari.no"
      - op: add
        path: "/spec/env/0"
        value:
          name: BASE_PATH
          value: "/agderfk-no"
      - op: add
        path: "/spec/env/1"
        value:
          name: CONSENT_API_URL
          value: http://fint-samtykke-service-backend:8080
      - op: replace
        path: "/spec/image"
        value: ghcr.io/fintlabs/fint-samtykke-frontend-v2
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/agderfk-no"
      - op: replace
        path: "/spec/ingress/hostname"
        value: "samtykke.novari.no"
    target:
      kind: Application
      name: fint-samtykke-frontend-v2
  - patch: |-
      - op: replace
        path: "/spec/basePath"
        value: "/agderfk-no"
      - op: replace
        path: "/spec/hostname"
        value: "samtykke.novari.no"
    target:
      kind: FLAISSso
      name: fint-samtykke-sso
