apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flais-sso.yaml
  - application.yaml
commonLabels:
  app.kubernetes.io/version: "latest"
  fintlabs.no/org-id: fintlabs.no
