name: Build Deploy

on:
  workflow_dispatch:
    inputs:
      org:
        description: 'Select organisation'
        required: true
        default: 'rogfk-no'
        type: choice
        options:
          - rogfk-no
          - agderfk-no
      environment:
        description: 'Select environment'
        required: true
        default: 'beta'
        type: choice
        options:
          - beta
          - api

permissions:
  contents: read
  packages: write

jobs:
  build-publish:
    uses: ./.github/workflows/.build-publish.yaml
    secrets: inherit
    with:
      base_path: "${{ inputs.environment == 'beta' && '/beta' || '' }}/${{ inputs.org }}"

  cluster-deploy:
    uses: ./.github/workflows/.cluster-deploy.yaml
    needs: build-publish
    secrets: inherit
    with:
      org: ${{ inputs.org }}
      environment: ${{ inputs.environment }}
      image-tags: ${{ needs.build-publish.outputs.image-tags }}
